name: cmc
channels:
  - conda-forge
  - dnachun
dependencies:
  - cartopy
  - cmocean
  - datashader
  - fx
  - geoviews
  - hvplot
  - ipython
  - ipykernel
  - nodejs
  - panel
  - pip
  - pip:
     - copernicus-marine-client
     - session-info
  - pyproj
  - speedtest-cli
  - python>=3.9,<3.12
