name: cmc-extra
channels:
  - conda-forge
  - dnachun
dependencies:
  - pip
  - fzf
  - bat
  - fx
  - ijq
  - jid
  - jless
  - python>=3.9
  - pip:
    - copernicus-marine-client
    - jello
    - jtbl
    - jellex
    - asciinema
  - ipython
  - ipykernel
  - fire
