name: cmt
channels:
  - conda-forge
  - dnachun
dependencies:
  - cartopy
  - cmocean
  - copernicusmarine
  - datashader
  - fire
  - fx
  - geoviews
  - hvplot
  - ipython
  - ipykernel
  - nodejs
  - panel
  - pip
  - pyproj
  - rasterio
  - rioxarray
  - session-info
  - speedtest-cli
  - python<3.13
